format = """
[░▒▓](#70474c)\
[ 󰤇 ](bg:#70474c fg:#dcdcdc)\
[](bg:#bf616a fg:#70474c)\
$directory\
[](fg:#bf616a bg:#3b2f30)\
$git_branch\
$git_status\
[](fg:#3b2f30 bg:#2e2e2e)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#2e2e2e bg:#1d1d1d)\
$time\
[ ](fg:#1d1d1d)\
\n$character"""
command_timeout = 2000

[directory]
style = "fg:#f8dfe2 bg:#bf616a"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#3b2f30"
format = '[[ $symbol $branch ](fg:#f8dfe2 bg:#3b2f30)]($style)'

[git_status]
style = "bg:#3b2f30"
format = '[[($all_status$ahead_behind )](fg:#f8dfe2 bg:#3b2f30)]($style)'

[nodejs]
symbol = ""
style = "bg:#2e2e2e"
format = '[[ $symbol ($version) ](fg:#f8dfe2 bg:#2e2e2e)]($style)'

[rust]
symbol = ""
style = "bg:#2e2e2e"
format = '[[ $symbol ($version) ](fg:#f8dfe2 bg:#2e2e2e)]($style)'

[golang]
symbol = "ﳑ"
style = "bg:#2e2e2e"
format = '[[ $symbol ($version) ](fg:#f8dfe2 bg:#2e2e2e)]($style)'

[php]
symbol = ""
style = "bg:#2e2e2e"
format = '[[ $symbol ($version) ](fg:#f8dfe2 bg:#2e2e2e)]($style)'

[time]
disabled = false
time_format = "%I:%M %P"
style = "bg:#1d1d1d"
format = '[[  $time ](fg:#d08791 bg:#1d1d1d)]($style)'
